### PR TITLE
Partial port to Qgis 3.0

### PR DESCRIPTION
**Pull request by olivierh65**
Atlas support not yet done.

### CODE REVIEW

**Comment by DelazJ** [comment]
Hi @olivierh65 Thanks for this contribution. It was on my list but not among the nearest to do so i really appreciate you do the port. 
Please give me a week and i'll come back to you with my review. For information, which branch did you use as basis?
Thanks.

**Comment by DelazJ** [comment]
Also, did you use tools/advices from https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3 or you did it manually?

**Comment by olivierh65** [comment]
I use advices and do the necessary changes manually.
I've not yet tried tools proposed in this page.

⁣Envoyé par BlueMail ​

Le 11 mars 2018 07:56, à 07:56, Harrissou Sant-anna <notifications@github.com> a écrit:

**Comment by olivierh65** [comment]
I use 0.2 (it's this one who is installed by qgis extension menu).


⁣Envoyé par BlueMail ​

Le 11 mars 2018 07:52, à 07:52, Harrissou Sant-anna <notifications@github.com> a écrit:

**Comment by DelazJ** [comment]
@olivierh65 I manually merged your commit in https://github.com/DelazJ/MapsPrinter/commit/f20717c7bd603c382583d8d26db776fc45311684 and pushed a new release of the plugin in plugins.qgis.org.
Tests are welcome and thanks for the initial push (and sorry for the delay)

**Pull request closed without merging**
